"""Enhanced Doctor portal schemas for surgical edits integration."""

# Enhanced schemas for surgical edits
from .appointments_enhanced import (
    AppointmentSummary,
    AppointmentCreateRequest,
    AppointmentUpdateRequest,
    AvailabilityRequest,
    AvailabilitySlot,
    AppointmentResponse,
    AppointmentList,
    AppointmentSearch,
    ConsultationCreate,
    ConsultationResponse,
    ConsultationUpdate,
    VitalSigns,
    PhysicalExamination,
    Diagnosis,
    TreatmentPlan,
    DoctorSchedule,
    ScheduleUpdate,
    AppointmentTypeEnum,
    AppointmentStatusEnum,
    PriorityEnum,
    DiagnosisTypeEnum,
    SeverityEnum,
    DayOfWeekEnum,
)

from .messages_enhanced import (
    SendMessageRequest,
    MessageTemplateRequest,
    ConversationSummary,
    MessageThread,
    MessageTemplate,
    MessageResponse,
    MessageStats,
    AttachmentUpload,
    AttachmentResponse,
    MessageSearch,
    ConversationCreate,
    ConversationResponse,
    MessageMarkReadRequest,
    MessageDeleteRequest,
    NotificationSettings,
    MessageTypeEnum,
    MessagePriorityEnum,
    MessageStatusEnum,
)

from .reports_enhanced import (
    CreateReportRequest,
    ReportSummary,
    VitalsData,
    CreateVitalsRequest,
    LabData,
    ImagingData,
    ReportData,
    ReportResponse,
    ReportUpdateRequest,
    ReportSearch,
    ReportStats,
    ReportTemplate,
    ReportSignature,
    ReportExport,
    ReportExportResponse,
    ReportTypeEnum,
    ReportStatusEnum,
    SpecialtyEnum,
)

# Note: Legacy and additional modules (appointments.py, prescriptions.py, etc.) are not exported
# to avoid import errors. Only enhanced schemas are re-exported here.

__all__ = [
    # Enhanced appointment schemas
    "AppointmentSummary",
    "AppointmentCreateRequest",
    "AppointmentUpdateRequest",
    "AvailabilityRequest",
    "AvailabilitySlot",
    "AppointmentResponse",
    "AppointmentList",
    "AppointmentSearch",
    "ConsultationCreate",
    "ConsultationResponse",
    "ConsultationUpdate",
    "VitalSigns",
    "PhysicalExamination",
    "Diagnosis",
    "TreatmentPlan",
    "DoctorSchedule",
    "ScheduleUpdate",
    "AppointmentTypeEnum",
    "AppointmentStatusEnum",
    "PriorityEnum",
    "DiagnosisTypeEnum",
    "SeverityEnum",
    "DayOfWeekEnum",
    
    # Enhanced message schemas
    "SendMessageRequest",
    "MessageTemplateRequest",
    "ConversationSummary",
    "MessageThread",
    "MessageTemplate",
    "MessageResponse",
    "MessageStats",
    "AttachmentUpload",
    "AttachmentResponse",
    "MessageSearch",
    "ConversationCreate",
    "ConversationResponse",
    "MessageMarkReadRequest",
    "MessageDeleteRequest",
    "NotificationSettings",
    "MessageTypeEnum",
    "MessagePriorityEnum",
    "MessageStatusEnum",
    
    # Enhanced report schemas
    "CreateReportRequest",
    "ReportSummary",
    "VitalsData",
    "CreateVitalsRequest",
    "LabData",
    "ImagingData",
    "ReportData",
    "ReportResponse",
    "ReportUpdateRequest",
    "ReportSearch",
    "ReportStats",
    "ReportTemplate",
    "ReportSignature",
    "ReportExport",
    "ReportExportResponse",
    "ReportTypeEnum",
    "ReportStatusEnum",
    "SpecialtyEnum",
    
]