from sqlalchemy import Column, ForeignKey, text, Integer, Float, Boolean, Numeric
from sqlalchemy.dialects.postgresql import UUID, DATE, TEXT, TIMESTAMP, JSONB, BIGINT
from sqlalchemy.orm import relationship
from app.db.base_class import Base

class Patient(Base):
    __tablename__ = "patients"
    __table_args__ = {"schema": "ehr"}

    patient_id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    user_id = Column(UUID(as_uuid=True), ForeignKey("core.users.user_id", ondelete="CASCADE"), unique=True)
    date_of_birth = Column(DATE)
    sex = Column(TEXT)
    phone = Column(TEXT)
    created_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=text("now()"))

    # Relationships
    user = relationship("User", back_populates="patient")

class Appointment(Base):
    __tablename__ = "appointments"
    __table_args__ = {"schema": "ehr"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    patient_id = Column(UUID(as_uuid=True), ForeignKey("ehr.patients.patient_id"), nullable=False)
    doctor_id = Column(UUID(as_uuid=True), ForeignKey("core.users.user_id"), nullable=False)
    hospital_id = Column(UUID(as_uuid=True), nullable=False)
    appointment_date = Column(TIMESTAMP(timezone=True), nullable=False)
    duration_minutes = Column(Integer, nullable=False)
    status = Column(TEXT, nullable=False)
    appointment_type = Column(TEXT, nullable=False)
    reason = Column(TEXT)
    notes = Column(TEXT)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True))

class Encounter(Base):
    __tablename__ = "encounters"
    __table_args__ = {"schema": "ehr"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    fhir_encounter_id = Column(TEXT)
    identifiers = Column(JSONB)
    patient_id = Column(UUID(as_uuid=True), ForeignKey("ehr.patients.patient_id"), nullable=False)
    status = Column(TEXT, nullable=False)
    class_code = Column(JSONB, nullable=False)
    class_display = Column(TEXT, nullable=False)
    type_code = Column(JSONB, nullable=False)
    type_display = Column(TEXT, nullable=False)
    service_type = Column(JSONB)
    priority = Column(JSONB)
    subject_id = Column(UUID(as_uuid=True), ForeignKey("ehr.patients.patient_id"))
    episode_of_care_id = Column(UUID(as_uuid=True))
    based_on = Column(JSONB)
    appointment_id = Column(UUID(as_uuid=True))
    period_start = Column(TIMESTAMP(timezone=True))
    period_end = Column(TIMESTAMP(timezone=True))
    length_value = Column(Float)
    length_unit = Column(TEXT)
    length_code = Column(TEXT)
    reason_code = Column(JSONB)
    reason_reference = Column(JSONB)
    diagnosis = Column(JSONB)
    account_id = Column(UUID(as_uuid=True))
    hospitalization = Column(JSONB)
    location = Column(JSONB)
    service_provider_id = Column(UUID(as_uuid=True))
    part_of_id = Column(UUID(as_uuid=True))
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True))

class LabOrder(Base):
    __tablename__ = "lab_orders"
    __table_args__ = {"schema": "ehr"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    fhir_service_request_id = Column(TEXT)
    identifiers = Column(JSONB)
    requisition = Column(JSONB)
    patient_id = Column(UUID(as_uuid=True), ForeignKey("ehr.patients.patient_id"), nullable=False)
    ordered_by = Column(UUID(as_uuid=True), ForeignKey("core.users.user_id"), nullable=False)
    encounter_id = Column(UUID(as_uuid=True), ForeignKey("ehr.encounters.id"))
    order_number = Column(TEXT, nullable=False)
    status = Column(TEXT, nullable=False)
    intent = Column(TEXT, nullable=False)
    priority = Column(TEXT, nullable=False)
    tests_ordered = Column(JSONB, nullable=False)
    category = Column(JSONB)
    clinical_indication = Column(TEXT)
    clinical_notes = Column(TEXT)
    reason_codes = Column(JSONB)
    supporting_info = Column(JSONB)
    ordered_date = Column(TIMESTAMP(timezone=True), nullable=False)
    required_by = Column(TIMESTAMP(timezone=True))
    occurrence_date = Column(TIMESTAMP(timezone=True))
    patient_instructions = Column(TEXT)
    lab_instructions = Column(TEXT)
    do_not_perform = Column(Boolean)
    specimen_required = Column(Boolean)
    specimen_type = Column(TEXT)
    specimen_instructions = Column(TEXT)
    fasting_required = Column(Boolean)
    performing_lab_id = Column(UUID(as_uuid=True))
    location_code = Column(JSONB)
    insurance_ids = Column(JSONB)
    cancelled_by = Column(UUID(as_uuid=True))
    cancelled_at = Column(TIMESTAMP(timezone=True))
    cancellation_reason = Column(TEXT)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True))

class LabResult(Base):
    __tablename__ = "lab_results"
    __table_args__ = {"schema": "ehr"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    fhir_observation_id = Column(TEXT)
    fhir_diagnostic_report_id = Column(TEXT)
    patient_id = Column(UUID(as_uuid=True), ForeignKey("ehr.patients.patient_id"), nullable=False)
    lab_order_id = Column(UUID(as_uuid=True), ForeignKey("ehr.lab_orders.id"))
    medical_record_id = Column(UUID(as_uuid=True))
    result_number = Column(TEXT, nullable=False)
    accession_number = Column(TEXT)
    test_name = Column(TEXT, nullable=False)
    test_code = Column(TEXT, nullable=False)
    test_category = Column(TEXT)
    panel_name = Column(TEXT)
    result_value = Column(TEXT, nullable=False)
    result_unit = Column(TEXT)
    result_type = Column(TEXT)
    reference_range = Column(TEXT)
    reference_range_low = Column(Float)
    reference_range_high = Column(Float)
    reference_range_text = Column(TEXT)
    is_abnormal = Column(Boolean)
    abnormality_type = Column(TEXT)
    is_critical = Column(Boolean)
    status = Column(TEXT, nullable=False)
    interpretation = Column(TEXT)
    clinical_significance = Column(TEXT)
    comments = Column(TEXT)
    performing_lab_name = Column(TEXT)
    performing_lab_id = Column(UUID(as_uuid=True))
    lab_director = Column(TEXT)
    specimen_type = Column(TEXT)
    specimen_collected_date = Column(TIMESTAMP(timezone=True))
    specimen_received_date = Column(TIMESTAMP(timezone=True))
    specimen_condition = Column(TEXT)
    test_date = Column(TIMESTAMP(timezone=True), nullable=False)
    resulted_date = Column(TIMESTAMP(timezone=True), nullable=False)
    verified_date = Column(TIMESTAMP(timezone=True))
    ordered_by = Column(UUID(as_uuid=True))
    performed_by = Column(TEXT)
    verified_by = Column(TEXT)
    resulted_by = Column(TEXT)
    report_file_url = Column(TEXT)
    attachments = Column(JSONB)
    test_method = Column(TEXT)
    instrument_id = Column(TEXT)
    previous_results = Column(JSONB)
    delta = Column(TEXT)
    trend = Column(TEXT)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True))

class LabReport(Base):
    __tablename__ = "lab_reports"
    __table_args__ = {"schema": "ehr"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    order_id = Column(UUID(as_uuid=True), ForeignKey("ehr.lab_orders.id"))
    patient_id = Column(UUID(as_uuid=True), ForeignKey("ehr.patients.patient_id"))
    report_date = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    title = Column(TEXT, nullable=False)
    summary = Column(TEXT)
    metrics = Column(JSONB)
    attachments = Column(JSONB)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))

class Prescription(Base):
    __tablename__ = "prescriptions"
    __table_args__ = {"schema": "ehr"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    fhir_medication_request_id = Column(TEXT)
    identifiers = Column(JSONB)
    patient_id = Column(UUID(as_uuid=True), ForeignKey("ehr.patients.patient_id"), nullable=False)
    doctor_id = Column(UUID(as_uuid=True), ForeignKey("core.users.user_id"), nullable=False)
    hospital_id = Column(UUID(as_uuid=True), nullable=False)
    encounter_id = Column(UUID(as_uuid=True), ForeignKey("ehr.encounters.id"))
    prescription_number = Column(TEXT, nullable=False)
    medicine_name = Column(TEXT, nullable=False)
    medicine_code = Column(TEXT)
    generic_name = Column(TEXT)
    brand_name = Column(TEXT)
    description = Column(TEXT)
    status = Column(TEXT, nullable=False)
    status_reason = Column(JSONB)
    intent = Column(TEXT, nullable=False)
    priority = Column(TEXT)
    prescribed_date = Column(TIMESTAMP(timezone=True), nullable=False)
    start_date = Column(DATE)
    end_date = Column(DATE)
    dosage = Column(TEXT, nullable=False)
    dosage_unit = Column(TEXT)
    frequency = Column(TEXT, nullable=False)
    route = Column(TEXT)
    duration = Column(TEXT)
    dosage_instructions = Column(JSONB)
    purpose = Column(TEXT)
    indication = Column(TEXT)
    reason_codes = Column(JSONB)
    notes = Column(TEXT)
    total_refills = Column(Integer)
    remaining_refills = Column(Integer)
    tablets_per_refill = Column(Integer)
    quantity = Column(Float)
    quantity_unit = Column(TEXT)
    days_supply = Column(Integer)
    dispense_request = Column(JSONB)
    expected_supply_duration = Column(Integer)
    allow_generic_substitution = Column(Boolean)
    substitution_reason = Column(TEXT)
    estimated_price = Column(Float)
    currency = Column(TEXT)
    prior_prescription_id = Column(UUID(as_uuid=True))
    is_signed = Column(Boolean)
    signed_at = Column(TIMESTAMP(timezone=True))
    signature_data = Column(TEXT)
    created_by = Column(UUID(as_uuid=True), nullable=False)
    prescribed_by = Column(UUID(as_uuid=True), nullable=False)
    last_modified_by = Column(UUID(as_uuid=True))
    cancelled_by = Column(UUID(as_uuid=True))
    cancelled_at = Column(TIMESTAMP(timezone=True))
    cancellation_reason = Column(TEXT)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True))

class Condition(Base):
    __tablename__ = "conditions"
    __table_args__ = {"schema": "ehr"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    fhir_condition_id = Column(TEXT)
    identifiers = Column(JSONB)
    patient_id = Column(UUID(as_uuid=True), ForeignKey("ehr.patients.patient_id"), nullable=False)
    encounter_id = Column(UUID(as_uuid=True), ForeignKey("ehr.encounters.id"))
    clinical_status = Column(TEXT, nullable=False)
    verification_status = Column(TEXT, nullable=False)
    category = Column(TEXT, nullable=False)
    severity = Column(TEXT)
    code = Column(JSONB, nullable=False)
    display_name = Column(TEXT, nullable=False)
    body_sites = Column(JSONB)
    onset_date = Column(DATE)
    onset_age = Column(Integer)
    onset_period_start = Column(DATE)
    onset_period_end = Column(DATE)
    onset_string = Column(TEXT)
    abatement_date = Column(DATE)
    abatement_age = Column(Integer)
    abatement_period_start = Column(DATE)
    abatement_period_end = Column(DATE)
    abatement_string = Column(TEXT)
    recorded_date = Column(TIMESTAMP(timezone=True), nullable=False)
    recorder_id = Column(UUID(as_uuid=True))
    asserter_id = Column(UUID(as_uuid=True))
    notes = Column(JSONB)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True))

class Observation(Base):
    __tablename__ = "observations"
    __table_args__ = {"schema": "ehr"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    fhir_observation_id = Column(TEXT)
    identifiers = Column(JSONB)
    patient_id = Column(UUID(as_uuid=True), ForeignKey("ehr.patients.patient_id"), nullable=False)
    encounter_id = Column(UUID(as_uuid=True), ForeignKey("ehr.encounters.id"))
    status = Column(TEXT, nullable=False)
    category = Column(TEXT, nullable=False)
    code = Column(JSONB, nullable=False)
    display_name = Column(TEXT, nullable=False)
    based_on = Column(JSONB)
    part_of = Column(JSONB)
    focus = Column(JSONB)
    effective_date = Column(TIMESTAMP(timezone=True))
    effective_period_start = Column(TIMESTAMP(timezone=True))
    effective_period_end = Column(TIMESTAMP(timezone=True))
    issued = Column(TIMESTAMP(timezone=True))
    performers = Column(JSONB)
    value_type = Column(TEXT)
    value_data = Column(JSONB)
    value_quantity = Column(Float)
    value_unit = Column(TEXT)
    value_string = Column(TEXT)
    value_boolean = Column(Boolean)
    value_integer = Column(Integer)
    data_absent_reason = Column(JSONB)
    interpretation = Column(JSONB)
    is_abnormal = Column(Boolean)
    notes = Column(JSONB)
    body_site = Column(JSONB)
    method = Column(JSONB)
    specimen_id = Column(UUID(as_uuid=True))
    device = Column(JSONB)
    reference_ranges = Column(JSONB)
    reference_range_low = Column(Float)
    reference_range_high = Column(Float)
    reference_range_text = Column(TEXT)
    has_member = Column(JSONB)
    derived_from = Column(JSONB)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True))

class AllergyIntolerance(Base):
    __tablename__ = "allergy_intolerances"
    __table_args__ = {"schema": "ehr"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    fhir_allergy_intolerance_id = Column(TEXT)
    identifiers = Column(JSONB)
    patient_id = Column(UUID(as_uuid=True), ForeignKey("ehr.patients.patient_id"), nullable=False)
    encounter_id = Column(UUID(as_uuid=True), ForeignKey("ehr.encounters.id"))
    clinical_status = Column(TEXT, nullable=False)
    verification_status = Column(TEXT, nullable=False)
    type = Column(TEXT, nullable=False)
    categories = Column(JSONB)
    criticality = Column(TEXT)
    code = Column(JSONB, nullable=False)
    display_name = Column(TEXT, nullable=False)
    onset_date = Column(DATE)
    onset_age = Column(Integer)
    onset_period_start = Column(DATE)
    onset_period_end = Column(DATE)
    onset_string = Column(TEXT)
    recorded_date = Column(TIMESTAMP(timezone=True), nullable=False)
    recorder_id = Column(UUID(as_uuid=True))
    asserter_id = Column(UUID(as_uuid=True))
    last_occurrence = Column(TIMESTAMP(timezone=True))
    notes = Column(JSONB)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True))

class Immunization(Base):
    __tablename__ = "immunizations"
    __table_args__ = {"schema": "ehr"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    fhir_immunization_id = Column(TEXT)
    identifiers = Column(JSONB)
    patient_id = Column(UUID(as_uuid=True), ForeignKey("ehr.patients.patient_id"), nullable=False)
    encounter_id = Column(UUID(as_uuid=True), ForeignKey("ehr.encounters.id"))
    status = Column(TEXT, nullable=False)
    status_reason = Column(JSONB)
    vaccine_code = Column(JSONB, nullable=False)
    vaccine_name = Column(TEXT, nullable=False)
    occurrence_date = Column(TIMESTAMP(timezone=True))
    occurrence_string = Column(TEXT)
    recorded = Column(TIMESTAMP(timezone=True), nullable=False)
    primary_source = Column(Boolean)
    report_origin = Column(JSONB)
    location_id = Column(UUID(as_uuid=True))
    manufacturer = Column(TEXT)
    lot_number = Column(TEXT)
    expiration_date = Column(DATE)
    site = Column(JSONB)
    route = Column(JSONB)
    dose_quantity = Column(Float)
    dose_unit = Column(TEXT)
    performer_id = Column(UUID(as_uuid=True))
    performer_function = Column(JSONB)
    reason_codes = Column(JSONB)
    reason_references = Column(JSONB)
    is_subpotent = Column(Boolean)
    subpotent_reasons = Column(JSONB)
    education_document_type = Column(TEXT)
    education_reference = Column(TEXT)
    education_publication_date = Column(DATE)
    education_presentation_date = Column(TIMESTAMP(timezone=True))
    program_eligibility = Column(JSONB)
    funding_source = Column(JSONB)
    notes = Column(JSONB)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True))

class RadiologyStudy(Base):
    __tablename__ = "radiology_studies"
    __table_args__ = {"schema": "ehr"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    accession_number = Column(TEXT, nullable=False)
    patient_id = Column(UUID(as_uuid=True), ForeignKey("ehr.patients.patient_id"), nullable=False)
    mrn = Column(TEXT)
    patient_name = Column(TEXT)
    age = Column(Integer)
    gender = Column(TEXT)
    dob = Column(DATE)
    order_date = Column(TIMESTAMP(timezone=True), nullable=False)
    scheduled_date = Column(TIMESTAMP(timezone=True), nullable=False)
    modality = Column(TEXT, nullable=False)
    body_part = Column(TEXT, nullable=False)
    study_description = Column(TEXT, nullable=False)
    indication = Column(TEXT)
    priority = Column(TEXT, nullable=False)
    status = Column(TEXT, nullable=False)
    ordering_physician = Column(TEXT)
    technologist = Column(TEXT)
    location = Column(TEXT)
    room = Column(TEXT)
    contrast = Column(Boolean)
    preparation = Column(TEXT)
    duration_minutes = Column(Integer)
    notes = Column(TEXT)
    insurance = Column(TEXT)
    authorization = Column("authorization", TEXT)
    cpt_code = Column(TEXT)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True))

class RadiologyReport(Base):
    __tablename__ = "radiology_reports"
    __table_args__ = {"schema": "ehr"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    study_id = Column(UUID(as_uuid=True), ForeignKey("ehr.radiology_studies.id"), nullable=False)
    radiologist_id = Column(UUID(as_uuid=True), ForeignKey("core.users.user_id"))
    report_date = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    findings = Column(TEXT, nullable=False)
    impression = Column(TEXT, nullable=False)
    recommendations = Column(TEXT)
    is_critical = Column(Boolean)
    status = Column(TEXT)

class Message(Base):
    __tablename__ = "messages"
    __table_args__ = {"schema": "ehr"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    sender_id = Column(UUID(as_uuid=True), ForeignKey("core.users.user_id"), nullable=False)
    recipient_id = Column(UUID(as_uuid=True), ForeignKey("core.users.user_id"), nullable=False)
    subject = Column(TEXT, nullable=False)
    message_content = Column(TEXT)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))

class LabSettings(Base):
    __tablename__ = "lab_settings"
    __table_args__ = {"schema": "ehr"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    settings_type = Column(TEXT, nullable=False)
    settings_data = Column(JSONB, nullable=False)
    version = Column(TEXT)
    is_active = Column(Boolean)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True))
    created_by = Column(UUID(as_uuid=True))