from sqlalchemy import Column, ForeignKey, text, Integer, Float, Boolean, Numeric
from sqlalchemy.dialects.postgresql import UUID, DATE, TEXT, TIMESTAMP, JSONB, BIGINT
from sqlalchemy.orm import relationship
from app.db.base_class import Base

class Bill(Base):
    __tablename__ = "bills"
    __table_args__ = {"schema": "financial"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    patient_id = Column(UUID(as_uuid=True), ForeignKey("ehr.patients.patient_id"), nullable=False)
    account_id = Column(UUID(as_uuid=True), nullable=False)
    bill_number = Column(TEXT, nullable=False)
    bill_date = Column(DATE, nullable=False)
    due_date = Column(DATE, nullable=False)
    bill_type = Column(TEXT, nullable=False)
    service_period_start = Column(DATE, nullable=False)
    service_period_end = Column(DATE, nullable=False)
    status = Column(TEXT, nullable=False)
    total_charges = Column(Numeric(15, 2), nullable=False)
    total_discounts = Column(Numeric(15, 2))
    total_adjustments = Column(Numeric(15, 2))
    total_tax = Column(Numeric(15, 2))
    total_amount = Column(Numeric(15, 2), nullable=False)
    paid_amount = Column(Numeric(15, 2))
    balance_due = Column(Numeric(15, 2), nullable=False)
    insurance_billed = Column(Boolean)
    insurance_billed_amount = Column(Numeric(15, 2))
    insurance_paid_amount = Column(Numeric(15, 2))
    insurance_adjustment = Column(Numeric(15, 2))
    patient_responsibility = Column(Numeric(15, 2))
    notes = Column(TEXT)
    internal_notes = Column(TEXT)
    submitted_date = Column(DATE)
    submitted_by = Column(UUID(as_uuid=True))
    cancelled_date = Column(TIMESTAMP(timezone=True))
    cancelled_by = Column(UUID(as_uuid=True))
    cancellation_reason = Column(TEXT)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True))
    created_by = Column(UUID(as_uuid=True), nullable=False)

class Payment(Base):
    __tablename__ = "payments"
    __table_args__ = {"schema": "financial"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    patient_id = Column(UUID(as_uuid=True), ForeignKey("ehr.patients.patient_id"), nullable=False)
    bill_id = Column(UUID(as_uuid=True), ForeignKey("financial.bills.id"))
    payment_number = Column(TEXT, nullable=False)
    payment_date = Column(TIMESTAMP(timezone=True), nullable=False)
    amount = Column(Numeric(15, 2), nullable=False)
    currency = Column(TEXT)
    payment_method = Column(TEXT, nullable=False)
    status = Column(TEXT, nullable=False)
    reference_number = Column(TEXT)
    authorization_code = Column(TEXT)
    card_last_four = Column(TEXT)
    card_type = Column(TEXT)
    bank_name = Column(TEXT)
    bank_reference = Column(TEXT)
    payer_name = Column(TEXT)
    payer_relationship = Column(TEXT)
    processed_date = Column(TIMESTAMP(timezone=True))
    processor_reference = Column(TEXT)
    is_refunded = Column(Boolean)
    refunded_amount = Column(Numeric(15, 2))
    refund_date = Column(TIMESTAMP(timezone=True))
    refund_reason = Column(TEXT)
    receipt_number = Column(TEXT)
    receipt_issued = Column(Boolean)
    notes = Column(TEXT)
    received_by = Column(UUID(as_uuid=True), nullable=False)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True))

class ChargeItem(Base):
    __tablename__ = "charge_items"
    __table_args__ = {"schema": "financial"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    fhir_charge_item_id = Column(TEXT)
    identifiers = Column(JSONB)
    patient_id = Column(UUID(as_uuid=True), ForeignKey("ehr.patients.patient_id"), nullable=False)
    encounter_id = Column(UUID(as_uuid=True), ForeignKey("ehr.encounters.id"))
    appointment_id = Column(UUID(as_uuid=True), ForeignKey("ehr.appointments.id"))
    service_code = Column(TEXT, nullable=False)
    service_name = Column(TEXT, nullable=False)
    service_category = Column(TEXT)
    code = Column(JSONB, nullable=False)
    status = Column(TEXT, nullable=False)
    occurrence_date = Column(TIMESTAMP(timezone=True), nullable=False)
    occurrence_period_start = Column(TIMESTAMP(timezone=True))
    occurrence_period_end = Column(TIMESTAMP(timezone=True))
    quantity = Column(Numeric(10, 2), nullable=False)
    quantity_unit = Column(TEXT)
    unit_price = Column(Numeric(15, 2), nullable=False)
    gross_amount = Column(Numeric(15, 2), nullable=False)
    factor_override = Column(Numeric(5, 2))
    price_override = Column(Numeric(15, 2))
    override_reason = Column(TEXT)
    discount_amount = Column(Numeric(15, 2))
    tax_amount = Column(Numeric(15, 2))
    net_amount = Column(Numeric(15, 2), nullable=False)
    performer_id = Column(UUID(as_uuid=True))
    performing_organization_id = Column(UUID(as_uuid=True))
    requesting_organization_id = Column(UUID(as_uuid=True))
    cost_center_id = Column(UUID(as_uuid=True))
    body_site = Column(JSONB)
    reason_codes = Column(JSONB)
    product_reference = Column(TEXT)
    product_code = Column(JSONB)
    account_id = Column(UUID(as_uuid=True))
    supporting_info = Column(JSONB)
    notes = Column(JSONB)
    entered_by = Column(UUID(as_uuid=True), nullable=False)
    entered_date = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    is_billed = Column(Boolean)
    billed_date = Column(TIMESTAMP(timezone=True))
    bill_id = Column(UUID(as_uuid=True), ForeignKey("financial.bills.id"))
    part_of_id = Column(UUID(as_uuid=True))
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True))

class InsuranceClaim(Base):
    __tablename__ = "insurance_claims"
    __table_args__ = {"schema": "financial"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    fhir_claim_id = Column(TEXT)
    insurance_id = Column(UUID(as_uuid=True), nullable=False)
    patient_id = Column(UUID(as_uuid=True), ForeignKey("ehr.patients.patient_id"), nullable=False)
    appointment_id = Column(UUID(as_uuid=True), ForeignKey("ehr.appointments.id"))
    claim_number = Column(TEXT, nullable=False)
    internal_claim_id = Column(TEXT, nullable=False)
    claim_type = Column(TEXT, nullable=False)
    service_type = Column(TEXT)
    service_date = Column(DATE, nullable=False)
    service_end_date = Column(DATE)
    submission_date = Column(DATE, nullable=False)
    received_date = Column(DATE)
    status = Column(TEXT, nullable=False)
    status_date = Column(TIMESTAMP(timezone=True), nullable=False)
    status_reason = Column(TEXT)
    billing_provider_id = Column(UUID(as_uuid=True), nullable=False)
    rendering_provider_id = Column(UUID(as_uuid=True))
    referring_provider_id = Column(UUID(as_uuid=True))
    services = Column(JSONB, nullable=False)
    diagnosis_codes = Column(JSONB, nullable=False)
    procedure_codes = Column(JSONB)
    total_charge_amount = Column(Float, nullable=False)
    allowed_amount = Column(Float)
    approved_amount = Column(Float)
    insurance_paid_amount = Column(Float)
    patient_paid_amount = Column(Float)
    patient_responsibility = Column(Float)
    contractual_adjustment = Column(Float)
    other_adjustments = Column(Float)
    write_off_amount = Column(Float)
    deductible_applied = Column(Float)
    copay_amount = Column(Float)
    coinsurance_amount = Column(Float)
    processed_date = Column(DATE)
    payment_date = Column(DATE)
    check_number = Column(TEXT)
    denial_reason = Column(TEXT)
    denial_codes = Column(JSONB)
    appeal_submitted = Column(Boolean)
    appeal_date = Column(DATE)
    appeal_outcome = Column(TEXT)
    appeal_notes = Column(TEXT)
    attachments = Column(JSONB)
    internal_notes = Column(TEXT)
    payer_notes = Column(TEXT)
    is_resubmission = Column(Boolean)
    original_claim_id = Column(UUID(as_uuid=True))
    resubmission_code = Column(TEXT)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True))

class InsuranceAuthorization(Base):
    __tablename__ = "insurance_authorizations"
    __table_args__ = {"schema": "financial"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    insurance_id = Column(UUID(as_uuid=True), nullable=False)
    patient_id = Column(UUID(as_uuid=True), ForeignKey("ehr.patients.patient_id"), nullable=False)
    authorization_number = Column(TEXT)
    request_date = Column(DATE, nullable=False)
    service_type = Column(TEXT, nullable=False)
    procedure_codes = Column(JSONB, nullable=False)
    diagnosis_codes = Column(JSONB, nullable=False)
    requesting_provider_id = Column(UUID(as_uuid=True), nullable=False)
    servicing_provider_id = Column(UUID(as_uuid=True))
    status = Column(TEXT, nullable=False)
    decision_date = Column(DATE)
    valid_from = Column(DATE)
    valid_to = Column(DATE)
    units_approved = Column(Integer)
    units_used = Column(Integer)
    clinical_notes = Column(TEXT)
    payer_notes = Column(TEXT)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True))

class FinancialTransaction(Base):
    __tablename__ = "financial_transactions"
    __table_args__ = {"schema": "financial"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    account_id = Column(UUID(as_uuid=True), nullable=False)
    transaction_date = Column(TIMESTAMP(timezone=True), nullable=False)
    transaction_type = Column(TEXT, nullable=False)
    charge_item_id = Column(UUID(as_uuid=True), ForeignKey("financial.charge_items.id"))
    payment_id = Column(UUID(as_uuid=True), ForeignKey("financial.payments.id"))
    debit_amount = Column(Numeric(15, 2))
    credit_amount = Column(Numeric(15, 2))
    running_balance = Column(Numeric(15, 2), nullable=False)
    description = Column(TEXT, nullable=False)
    reference_number = Column(TEXT)
    posted_by = Column(UUID(as_uuid=True), nullable=False)
    posted_date = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    is_reversed = Column(Boolean)
    reversed_by_id = Column(UUID(as_uuid=True))
    reversal_reason = Column(TEXT)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
