GRANT USAGE ON SCHEMA core, ehr, ops, ref, staging TO fiattib_app_rw, fiattib_app_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO fiattib_app_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA ehr  GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO fiattib_app_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA staging GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO fiattib_app_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT SELECT ON TABLES TO fiattib_app_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA ehr  GRANT SELECT ON TABLES TO fiattib_app_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA staging GRANT SELECT ON TABLES TO fiattib_app_ro;
