services:
  orthanc:
    image: jodogne/orthanc-plugins:1.12.3
    container_name: fiattib-orthanc
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - ./config/orthanc.json:/etc/orthanc/orthanc.json
      - orthanc-db:/var/lib/orthanc/db
    restart: unless-stopped
    networks:
      - pacs-network

  nginx-cors:
    image: nginx:alpine
    container_name: fiattib-nginx-cors
    ports:
      - "8043:8043"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - orthanc
    restart: unless-stopped
    networks:
      - pacs-network

  ohif:
    image: ohif/app:v3.9.2
    container_name: fiattib-ohif
    ports:
      - "3000:80"
    environment:
      - PUBLIC_URL=/
    volumes:
      - orthanc-db:/some/path/if-needed
      - ./ohif/app-config.js:/usr/share/nginx/html/app-config.js:ro

  monai:
    image: projectmonai/monailabel:latest
    container_name: fiattib-monai
    ports:
      - "8000:8000"
    volumes:
      - /c/Users/kubay/monai/apps:/app/apps
      - /c/Users/kubay/monai/datasets:/datasets
    working_dir: /app
    command: [
      "monailabel", "start_server",
      "--app", "apps/radiology",
      "--studies", "/datasets",
      "--conf", "models", "deepedit"
    ]
    restart: unless-stopped


volumes:
  orthanc-db:

networks:
  pacs-network:
    driver: bridge
