"""Enhanced Patient portal schemas for surgical edits integration."""

# Enhanced schemas for surgical edits
from .profile_enhanced import (
    ProfileOut,
    ProfileUpdateRequest,
    VitalSignsRequest,
    AllergyUpdateRequest,
    ChronicConditionUpdateRequest,
    ProfileStats,
    ProfileExportRequest,
    ProfileExportResponse,
    VitalStat,
    ImmunizationRec,
    InsuranceInfo,
    EmergencyContact,
    GenderEnum,
    MaritalStatusEnum,
    LanguageEnum,
    # Merged additional schemas
    PatientSettings,
    PatientProfile,
    PatientAppointment,
    AppointmentCreate,
    AppointmentRow,
    AppointmentPatch,
    AppointmentRequest,
    Notifications,
    Privacy,
    Preferences,
    SettingsBlob,
    FHIRExportRequest,
    FHIREraseRequest,
    FHIRExportResult,
    FHIREraseResult,
    ConfirmationCodeRequest,
    ConfirmationCodeResult,
)

from .prescription_enhanced import (
    PrescriptionSummary,
    RefillRequest,
    RefillTaskStatus,
    PrescriptionDetail,
    PrescriptionListResponse,
    PrescriptionSearchRequest,
    RefillHistory,
    PrescriptionStats,
    MedicationInteractionCheck,
    MedicationInteractionResponse,
    PrescriptionReminderRequest,
    PrescriptionReminderResponse,
    PrescriptionStatusEnum,
    RefillStatusEnum,
    TaskStatusEnum,
)

from .records_enhanced import (
    VitalSignsRecord,
    LabResultRecord,
    ImagingRecord,
    ConsultationRecord,
    ProcedureRecord,
    MedicalRecord,
    RecordsListResponse,
    RecordsSearchRequest,
    RecordsStats,
    RecordExportRequest,
    RecordExportResponse,
    RecordShareRequest,
    RecordShareResponse,
    RecordAccessLog,
    RecordTypeEnum,
    RecordStatusEnum,
    PriorityEnum,
)

from .doctorsearch_enhanced import (
    DoctorSearchRequest,
    DoctorSummary,
    DoctorDetail,
    DoctorSearchResponse,
    SearchFacets,
    DoctorAvailabilityRequest,
    DoctorAvailabilityResponse,
    DoctorReview,
    DoctorStats,
    FavoriteDoctorRequest,
    FavoriteDoctorResponse,
    FavoriteDoctorsList,
    SpecialtyEnum,
    AvailabilityStatusEnum,
)

__all__ = [
    # Enhanced profile schemas
    "ProfileOut",
    "ProfileUpdateRequest",
    "VitalSignsRequest",
    "AllergyUpdateRequest",
    "ChronicConditionUpdateRequest",
    "ProfileStats",
    "ProfileExportRequest",
    "ProfileExportResponse",
    "VitalStat",
    "ImmunizationRec",
    "InsuranceInfo",
    "EmergencyContact",
    "GenderEnum",
    "MaritalStatusEnum",
    "LanguageEnum",
    # Merged additional patient portal schemas
    "PatientSettings",
    "PatientProfile",
    "PatientAppointment",
    "AppointmentCreate",
    "AppointmentRow",
    "AppointmentPatch",
    "AppointmentRequest",
    "Notifications",
    "Privacy",
    "Preferences",
    "SettingsBlob",
    "FHIRExportRequest",
    "FHIREraseRequest",
    "FHIRExportResult",
    "FHIREraseResult",
    "ConfirmationCodeRequest",
    "ConfirmationCodeResult",
    
    # Enhanced prescription schemas
    "PrescriptionSummary",
    "RefillRequest",
    "RefillTaskStatus",
    "PrescriptionDetail",
    "PrescriptionListResponse",
    "PrescriptionSearchRequest",
    "RefillHistory",
    "PrescriptionStats",
    "MedicationInteractionCheck",
    "MedicationInteractionResponse",
    "PrescriptionReminderRequest",
    "PrescriptionReminderResponse",
    "PrescriptionStatusEnum",
    "RefillStatusEnum",
    "TaskStatusEnum",
    
    # Enhanced records schemas
    "VitalSignsRecord",
    "LabResultRecord",
    "ImagingRecord",
    "ConsultationRecord",
    "ProcedureRecord",
    "MedicalRecord",
    "RecordsListResponse",
    "RecordsSearchRequest",
    "RecordsStats",
    "RecordExportRequest",
    "RecordExportResponse",
    "RecordShareRequest",
    "RecordShareResponse",
    "RecordAccessLog",
    "RecordTypeEnum",
    "RecordStatusEnum",
    "PriorityEnum",
    
    # Enhanced doctor search schemas
    "DoctorSearchRequest",
    "DoctorSummary",
    "DoctorDetail",
    "DoctorSearchResponse",
    "SearchFacets",
    "DoctorAvailabilityRequest",
    "DoctorAvailabilityResponse",
    "DoctorReview",
    "DoctorStats",
    "FavoriteDoctorRequest",
    "FavoriteDoctorResponse",
    "FavoriteDoctorsList",
    "SpecialtyEnum",
    "AvailabilityStatusEnum",
]
