"""Enhanced Admin portal schemas for surgical edits integration."""

# Enhanced schemas for surgical edits
from .rbac_enhanced import (
    RBACPolicy,
    RolePolicy,
    ClinicScope,
    UserRoleAssignment,
    PermissionCheck,
    PermissionCheckResponse,
    PolicyCreateRequest,
    PolicyUpdateRequest,
    RoleAssignmentRequest,
    RoleAssignmentUpdateRequest,
    RBACStats,
    PolicySearchRequest,
    PolicyListResponse,
    UserRoleSearchRequest,
    UserRoleListResponse,
    RoleEnum,
    ScopeEnum,
    PolicyStatusEnum,
)

from .fhir_registry_enhanced import (
    FHIROrganization,
    FHIRLocation,
    FHIRPractitioner,
    FHIRPractitionerRole,
    OrganizationCreateRequest,
    OrganizationUpdateRequest,
    LocationCreateRequest,
    LocationUpdateRequest,
    PractitionerCreateRequest,
    PractitionerUpdateRequest,
    PractitionerRoleCreateRequest,
    PractitionerRoleUpdateRequest,
    FHIRRegistryStats,
    RegistrySearchRequest,
    RegistryListResponse,
    OrganizationStatusEnum,
    LocationStatusEnum,
    PractitionerStatusEnum,
    LocationTypeEnum,
    PhysicalTypeEnum,
)

from .global_settings_enhanced import (
    GlobalSetting,
    SettingCreateRequest,
    SettingUpdateRequest,
    NotificationSettings,
    EmailSettings,
    SMSSettings,
    PaymentSettings,
    SecuritySettings,
    AITabibSettings,
    IntegrationSettings,
    SystemSettings,
    SettingsSearchRequest,
    SettingsListResponse,
    SettingsStats,
    SettingBulkUpdateRequest,
    SettingBulkUpdateResponse,
    SettingTypeEnum,
    SettingScopeEnum,
    SettingCategoryEnum,
)

from .audit_logs_enhanced import (
    AuditLog,
    AuditLogSearchRequest,
    AuditLogListResponse,
    AuditLogStats,
    AuditLogExportRequest,
    AuditLogExportResponse,
    AuditLogAlert,
    AuditLogAlertCreateRequest,
    AuditLogAlertUpdateRequest,
    AuditLogRetentionPolicy,
    AuditLogRetentionPolicyCreateRequest,
    AuditLogRetentionPolicyUpdateRequest,
    AuditActionEnum,
    AuditResourceEnum,
    AuditSeverityEnum,
)

# Legacy schemas (for backward compatibility)
# Note: legacy schemas removed/not present; keep exports minimal to avoid import errors.

__all__ = [
    # Enhanced RBAC schemas
    "RBACPolicy",
    "RolePolicy",
    "ClinicScope",
    "UserRoleAssignment",
    "PermissionCheck",
    "PermissionCheckResponse",
    "PolicyCreateRequest",
    "PolicyUpdateRequest",
    "RoleAssignmentRequest",
    "RoleAssignmentUpdateRequest",
    "RBACStats",
    "PolicySearchRequest",
    "PolicyListResponse",
    "UserRoleSearchRequest",
    "UserRoleListResponse",
    "RoleEnum",
    "ScopeEnum",
    "PolicyStatusEnum",
    
    # Enhanced FHIR registry schemas
    "FHIROrganization",
    "FHIRLocation",
    "FHIRPractitioner",
    "FHIRPractitionerRole",
    "OrganizationCreateRequest",
    "OrganizationUpdateRequest",
    "LocationCreateRequest",
    "LocationUpdateRequest",
    "PractitionerCreateRequest",
    "PractitionerUpdateRequest",
    "PractitionerRoleCreateRequest",
    "PractitionerRoleUpdateRequest",
    "FHIRRegistryStats",
    "RegistrySearchRequest",
    "RegistryListResponse",
    "OrganizationStatusEnum",
    "LocationStatusEnum",
    "PractitionerStatusEnum",
    "LocationTypeEnum",
    "PhysicalTypeEnum",
    
    # Enhanced global settings schemas
    "GlobalSetting",
    "SettingCreateRequest",
    "SettingUpdateRequest",
    "NotificationSettings",
    "EmailSettings",
    "SMSSettings",
    "PaymentSettings",
    "SecuritySettings",
    "AITabibSettings",
    "IntegrationSettings",
    "SystemSettings",
    "SettingsSearchRequest",
    "SettingsListResponse",
    "SettingsStats",
    "SettingBulkUpdateRequest",
    "SettingBulkUpdateResponse",
    "SettingTypeEnum",
    "SettingScopeEnum",
    "SettingCategoryEnum",
    
    # Enhanced audit logs schemas
    "AuditLog",
    "AuditLogSearchRequest",
    "AuditLogListResponse",
    "AuditLogStats",
    "AuditLogExportRequest",
    "AuditLogExportResponse",
    "AuditLogAlert",
    "AuditLogAlertCreateRequest",
    "AuditLogAlertUpdateRequest",
    "AuditLogRetentionPolicy",
    "AuditLogRetentionPolicyCreateRequest",
    "AuditLogRetentionPolicyUpdateRequest",
    "AuditActionEnum",
    "AuditResourceEnum",
    "AuditSeverityEnum",
    
    # Legacy schemas (for backward compatibility)
    "ClinicBase",
    "ClinicCreate",
    "ClinicUpdate",
    "ClinicInDB",
    "DepartmentBase",
    "DepartmentCreate",
    "DepartmentUpdate",
    "DepartmentInDB",
    "PricingBase",
    "PricingCreate",
    "PricingUpdate",
    "PricingInDB",
    "SettingsBase",
    "SettingsCreate",
    "SettingsUpdate",
    "SettingsInDB",
    "StaffBase",
    "StaffCreate",
    "StaffUpdate",
    "StaffInDB",
]
